const covers = {
"ASTRAL CHAIN": "covers/ASTRAL CHAIN.jpeg",
"Badland: Game of the Year Edition": "covers/Badland Game of the Year Edition.jpeg",
"Batman: The Enemy Within": "covers/Batman The Enemy Within.jpeg",
"Batman - The Telltale Series": "covers/Batman - The Telltale Series.jpeg",
"Big Brain Academy: Brain vs. Brain": "covers/Big Brain Academy Brain vs. Brain.jpeg",
"Brothers: A Tale of Two Sons": "covers/Brothers A Tale of Two Sons.jpeg",
"Burnout Paradise Remastered": "covers/Burnout Paradise Remastered.jpeg",
"Captain Toad: Treasure Tracker and Captain Toad: Treasure Tracker - Special Episode Bundle": "covers/Captain Toad Treasure Tracker and Captain Toad Treasure Tracker - Special Episode Bundle.jpeg",
"Chants of Sennaar": "covers/Chants of Sennaar.jpeg",
"Chicory: A Colorful Tale": "covers/Chicory A Colorful Tale.jpeg",
"DAVE THE DIVER": "covers/DAVE THE DIVER.jpeg",
"Dead Cells": "covers/Dead Cells.jpeg",
"Dead Cells: Medley of Pain Bundle": "covers/Dead Cells Medley of Pain Bundle.jpeg",
"Disco Elysium - The Final Cut": "covers/Disco Elysium - The Final Cut.jpeg",
"Divinity: Original Sin 2 - Definitive Edition": "covers/Divinity Original Sin 2 - Definitive Edition.jpeg",
"Door Kickers": "covers/Door Kickers.jpeg",
"DYSMANTLE": "covers/DYSMANTLE.jpeg",
"FAR: Changing Tides": "covers/FAR Changing Tides.jpeg",
"FAR: Lone Sails": "covers/FAR Lone Sails.jpeg",
"GRID Autosport": "covers/GRID Autosport.jpeg",
"Hades": "covers/Hades.jpeg",
"Hogwarts Legacy: Deluxe Edition": "covers/Hogwarts Legacy Deluxe Edition.jpeg",
"Hollow Knight": "covers/Hollow Knight.jpeg",
"Immortals Fenyx Rising": "covers/Immortals Fenyx Rising.jpeg",
"INSIDE": "covers/INSIDE.jpeg",
"Into the Breach": "covers/Into the Breach.jpeg",
"The Legend of Zelda: Breath of the Wild": "covers/The Legend of Zelda Breath of the Wild.jpeg",
"The Legend of Zelda: Breath of the Wild Expansion Pass": "covers/The Legend of Zelda Breath of the Wild Expansion Pass.jpeg",
"The Legend of Zelda: Echoes of Wisdom": "covers/The Legend of Zelda Echoes of Wisdom.jpeg",
"The Legend of Zelda: Link’s Awakening": "covers/The Legend of Zelda Link’s Awakening.jpeg",
"The Legend of Zelda: Tears of the Kingdom": "covers/The Legend of Zelda Tears of the Kingdom.jpeg",
"LEGO Bricktales": "covers/LEGO Bricktales.jpeg",
"LEGO Builder's Journey": "covers/LEGO Builder's Journey.jpeg",
"LEGO CITY Undercover": "covers/LEGO CITY Undercover.jpeg",
"LEGO DC Super-Villains Deluxe Edition": "covers/LEGO DC Super-Villains Deluxe Edition.jpeg",
"LEGO Marvel Super Heroes": "covers/LEGO Marvel Super Heroes.jpeg",
"LEGO Marvel Super Heroes 2": "covers/LEGO Marvel Super Heroes 2.jpeg",
"LEGO Star Wars: The Skywalker Saga": "covers/LEGO Star Wars The Skywalker Saga.jpeg",
"LEGO Worlds": "covers/LEGO Worlds.jpeg",
"LIMBO": "covers/LIMBO.jpeg",
"Linelight": "covers/Linelight.jpeg",
"Mario + Rabbids Kingdom Battle": "covers/Mario + Rabbids Kingdom Battle.jpeg",
"Mario + Rabbids Kingdom Battle Donkey Kong Adventure": "covers/Mario + Rabbids Kingdom Battle Donkey Kong Adventure.jpeg",
"Mario + Rabbids Sparks of Hope": "covers/Mario + Rabbids Sparks of Hope.jpeg",
"Mario vs. Donkey Kong": "covers/Mario vs. Donkey Kong.jpeg",
"Metroid Dread": "covers/Metroid Dread.jpeg",
"Monster Boy and the Cursed Kingdom": "covers/Monster Boy and the Cursed Kingdom.jpeg",
"Monument Valley: The Collection": "covers/Monument Valley The Collection.jpeg",
"Moonlighter": "covers/Moonlighter.jpeg",
"Need for Speed Hot Pursuit Remastered": "covers/Need for Speed Hot Pursuit Remastered.jpeg",
"NieR:Automata The End of YoRHa Edition": "covers/NieRAutomata The End of YoRHa Edition.jpeg",
"No Man's Sky": "covers/No Man's Sky.jpeg",
"Ori and the Blind Forest: Definitive Edition": "covers/Ori and the Blind Forest Definitive Edition.jpeg",
"Outer Wilds": "covers/Outer Wilds.jpeg",
"The Pedestrian": "covers/The Pedestrian.jpeg",
"Pokémon Legends: Arceus": "covers/Pokémon Legends Arceus.jpeg",
"Prince of Persia The Lost Crown": "covers/Prince of Persia The Lost Crown.jpeg",
"Red Dead Redemption": "covers/Red Dead Redemption.jpeg",
"RUINER": "covers/RUINER.jpeg",
"Scott Pilgrim vs. The World: The Game – Complete Edition": "covers/Scott Pilgrim vs. The World The Game – Complete Edition.jpeg",
"Sky: Children of the Light": "covers/Sky Children of the Light.jpeg",
"SnowRunner": "covers/SnowRunner.jpeg",
"SnowRunner - Jack of All Treads Tire Pack": "covers/SnowRunner - Jack of All Treads Tire Pack.jpeg",
"SnowRunner - The Mastodon": "covers/SnowRunner - The Mastodon.jpeg",
"SnowRunner - Year 1 Pass + Year 2 Pass + Year 3 Pass": "covers/SnowRunner - Year 1 Pass + Year 2 Pass + Year 3 Pass.jpeg",
"Spaceland": "covers/Spaceland.jpeg",
"Stardew Valley": "covers/Stardew Valley.jpeg",
"SteamWorld Dig": "covers/SteamWorld Dig.jpeg",
"SteamWorld Dig 2": "covers/SteamWorld Dig 2.jpeg",
"SteamWorld Heist II": "covers/SteamWorld Heist II.jpeg",
"SteamWorld Heist: Ultimate Edition": "covers/SteamWorld Heist Ultimate Edition.jpeg",
"SteamWorld Quest: Hand of Gilgamech": "covers/SteamWorld Quest Hand of Gilgamech.jpeg",
"Super Mario 3D World + Bowser’s Fury": "covers/Super Mario 3D World + Bowser’s Fury.jpeg",
"Super Mario Bros. Wonder": "covers/Super Mario Bros. Wonder.jpeg",
"Super Mario Galaxy + Super Mario Galaxy 2": "covers/Super Mario Galaxy + Super Mario Galaxy 2.jpeg",
"Super Mario Odyssey": "covers/Super Mario Odyssey.jpeg",
"Teenage Mutant Ninja Turtles: Shredder's Revenge": "covers/Teenage Mutant Ninja Turtles Shredder's Revenge.jpeg",
"Teenage Mutant Ninja Turtles: Splintered Fate": "covers/Teenage Mutant Ninja Turtles Splintered Fate.jpeg",
"Teenage Mutant Ninja Turtles: The Cowabunga Collection": "covers/Teenage Mutant Ninja Turtles The Cowabunga Collection.jpeg",
"Tents and Trees": "covers/Tents and Trees.jpeg",
"Tony Hawk's Pro Skater 1 + 2": "covers/Tony Hawk's Pro Skater 1 + 2.jpeg",
"Warframe": "covers/Warframe.jpeg",
"Warhammer 40,000: Mechanicus": "covers/Warhammer 40,000 Mechanicus.jpeg",
"The Witcher 3: Wild Hunt — Complete Edition": "covers/The Witcher 3 Wild Hunt — Complete Edition.jpeg",
"World of Goo 2": "covers/World of Goo 2.jpeg",
"Wreckfest": "covers/Wreckfest.jpeg",
"XCOM 2 Collection": "covers/XCOM 2 Collection.jpeg",
};

